'use client';

import Link from 'next/link';
import { Coins, UploadCloud, Download, Trophy } from 'lucide-react';
import { Skeleton } from '@/components/ui/Skeleton';

export default function StatsGrid({ stats, loading }) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
      {/* Academic Points */}
      <div className="group relative bg-[var(--card-bg)] border border-[var(--card-border)] rounded-[2.5rem] p-8 shadow-sm hover:border-amber-500/30 transition-all duration-500 hover:-translate-y-1">
        <div className="absolute inset-0 rounded-[2.5rem] bg-gradient-to-br from-amber-500/[0.02] to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
        <div className="flex justify-between items-start relative z-10">
          <div className="space-y-3">
            <span className="text-[9px] font-black uppercase tracking-widest text-slate-700 dark:text-slate-400">Academic Points</span>
            <h3 className="text-4xl font-black tracking-tight text-amber-500">
              {loading ? <Skeleton className="w-16 h-10 rounded-lg animate-pulse" /> : stats.points}
            </h3>
            <p className="text-[9px] font-bold text-slate-700 dark:text-slate-400 uppercase tracking-widest mt-1">Currency for downloads</p>
          </div>
          <div className="w-12 h-12 rounded-2xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center text-amber-500 shadow-xl group-hover:scale-110 transition-transform duration-500">
            <Coins size={22} className="animate-pulse" />
          </div>
        </div>
      </div>

      {/* Uploaded Notes */}
      <Link href="/dashboard/uploaded-notes" className="group relative bg-[var(--card-bg)] border border-[var(--card-border)] rounded-[2.5rem] p-8 shadow-sm hover:border-purple-500/30 transition-all duration-500 hover:-translate-y-1 block">
        <div className="absolute inset-0 rounded-[2.5rem] bg-gradient-to-br from-purple-500/[0.02] to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
        <div className="flex justify-between items-start relative z-10">
          <div className="space-y-3">
            <span className="text-[9px] font-black uppercase tracking-widest text-slate-700 dark:text-slate-400">Total Uploaded</span>
            <h3 className="text-4xl font-black tracking-tight text-purple-500">
              {loading ? <Skeleton className="w-16 h-10 rounded-lg animate-pulse" /> : stats.uploads}
            </h3>
            <p className="text-[9px] font-bold text-slate-700 dark:text-slate-400 uppercase tracking-widest mt-1">Shared study materials</p>
          </div>
          <div className="w-12 h-12 rounded-2xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-500 shadow-xl group-hover:scale-110 transition-transform duration-500">
            <UploadCloud size={22} />
          </div>
        </div>
      </Link>

      {/* Total Downloads Received */}
      <div className="group relative bg-[var(--card-bg)] border border-[var(--card-border)] rounded-[2.5rem] p-8 shadow-sm hover:border-blue-500/30 transition-all duration-500 hover:-translate-y-1">
        <div className="absolute inset-0 rounded-[2.5rem] bg-gradient-to-br from-blue-500/[0.02] to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
        <div className="flex justify-between items-start relative z-10">
          <div className="space-y-3">
            <span className="text-[9px] font-black uppercase tracking-widest text-slate-700 dark:text-slate-400">Total Downloads</span>
            <h3 className="text-4xl font-black tracking-tight text-blue-500">
              {loading ? <Skeleton className="w-16 h-10 rounded-lg animate-pulse" /> : stats.downloads}
            </h3>
            <p className="text-[9px] font-bold text-slate-700 dark:text-slate-400 uppercase tracking-widest mt-1">Generated by other peers</p>
          </div>
          <div className="w-12 h-12 rounded-2xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center text-blue-500 shadow-xl group-hover:scale-110 transition-transform duration-500">
            <Download size={22} />
          </div>
        </div>
      </div>

      {/* Leaderboard Position */}
      <Link href="/leaderboard" className="group relative bg-[var(--card-bg)] border border-[var(--card-border)] rounded-[2.5rem] p-8 shadow-sm hover:border-emerald-500/30 transition-all duration-500 hover:-translate-y-1 block">
        <div className="absolute inset-0 rounded-[2.5rem] bg-gradient-to-br from-emerald-500/[0.02] to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
        <div className="flex justify-between items-start relative z-10">
          <div className="space-y-3">
            <span className="text-[9px] font-black uppercase tracking-widest text-slate-700 dark:text-slate-400">Leaderboard Rank</span>
            <h3 className="text-4xl font-black tracking-tight text-emerald-500">
              {loading ? <Skeleton className="w-20 h-10 rounded-lg animate-pulse" /> : stats.rank}
            </h3>
            <p className="text-[9px] font-bold text-slate-700 dark:text-slate-400 uppercase tracking-widest mt-1">Top peers list position</p>
          </div>
          <div className="w-12 h-12 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-500 shadow-xl group-hover:scale-110 transition-transform duration-500">
            <Trophy size={22} />
          </div>
        </div>
      </Link>
    </div>
  );
}
